# Generated by Django 5.0.6 on 2024-05-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0002_rename_sobrenome_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='sobrenome',
        ),
    ]
