# Generated by Django 5.0.6 on 2024-05-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0003_login_rename_email_usuario_sobrenome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='imagens/')),
            ],
        ),
    ]
