# Generated by Django 5.0.6 on 2024-05-29 23:36

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0004_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Produto',
        )
    ]
