# Generated by Django 5.0.6 on 2024-05-29 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0005_auto_20240529_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Usuario',
        ),
    ]
