# Generated by Django 5.0.6 on 2024-05-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0007_auto_20240529_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
