# Generated by Django 5.0.6 on 2024-05-30 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0008_produto_foto_alter_produto_quantidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
